# Generated by Django 5.1.15 on 2026-07-09 09:05

import apps.accounts.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                unique=True,
                validators=[apps.accounts.validators.validate_ethiopian_phone],
                verbose_name="phone number",
            ),
        ),
    ]
