# Generated by Django 5.1.15 on 2026-07-06 08:02

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Required for the range-overlap ExclusionConstraint below (FR-122).
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_start", models.DateTimeField(db_index=True)),
                ("scheduled_end", models.DateTimeField()),
                ("slot", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("vendor", "Vendor"),
                            ("admin", "Admin"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("cancellation_reason", models.CharField(blank=True, max_length=200)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.service",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_start"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "status"],
                        name="bookings_bo_vendor__022002_idx",
                    ),
                    models.Index(
                        fields=["customer", "status"],
                        name="bookings_bo_custome_0cbf77_idx",
                    ),
                ],
                "constraints": [
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("status__in", ["pending", "confirmed"])),
                        expressions=[("vendor", "="), ("slot", "&&")],
                        name="excl_vendor_overlapping_active_booking",
                    )
                ],
            },
        ),
    ]
