# Generated by Django 5.1.15 on 2026-07-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
